The corresponding R commands are put as a comment at the start of the cell

# 3. Sequences of Numbers

In [1]:
# a  <- [1,2,3]
a =[1,2,3]
a[1]
print(a)

[1, 2, 3]


In [2]:
#1:20
list(range(1,21))
#python does not include the end of the sequence

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [3]:
#pi:10
import math
print(list(range(math.pi,10)))
#python forces the range() parameters to be integers

TypeError: 'float' object cannot be interpreted as an integer

In [4]:
#pi:10
print([i + math.pi for i in range(0,7)])

[3.141592653589793, 4.141592653589793, 5.141592653589793, 6.141592653589793, 7.141592653589793, 8.141592653589793, 9.141592653589793]


In [5]:
#15:1
print('1st attempt')
print(list(range(15,1)))
print('2nd attempt')
print(list(range(15,0,-1)))
#python treats sequences as increasing numbers unless specified otherwise

1st attempt
[]
2nd attempt
[15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [6]:
#seq(0, 10, by=0.5)
print(list( range(0,11,0.5)))

TypeError: 'float' object cannot be interpreted as an integer

In [7]:
#seq(0, 10, by=0.5)
by = 1/2
print([by*i for i in range(0, int(10/by)+1)])
#seq(0, 20, by=2)
list(range(0,21,2))

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0]


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [8]:
#seq(5, 10, length=30)
#no python equivalent

In [9]:
#my_seq <- seq(5, 10, length=30)
start = 5
end = 10
nb = 30
my_seq = [start + (end-start)/(nb-1)*i for i in range(nb)]
print(my_seq)
print(len(my_seq))

[5.0, 5.172413793103448, 5.344827586206897, 5.517241379310345, 5.689655172413794, 5.862068965517241, 6.0344827586206895, 6.206896551724138, 6.379310344827586, 6.551724137931035, 6.724137931034483, 6.896551724137931, 7.068965517241379, 7.241379310344827, 7.413793103448276, 7.586206896551724, 7.758620689655173, 7.931034482758621, 8.10344827586207, 8.275862068965518, 8.448275862068966, 8.620689655172415, 8.793103448275861, 8.96551724137931, 9.137931034482758, 9.310344827586206, 9.482758620689655, 9.655172413793103, 9.827586206896552, 10.0]
30


In [10]:
#1:length(my_seq)
#seq_along(my_seq)
print(list(range(len(my_seq))))
print([1+i for i in range(len(my_seq))])
#python's indexes start at 0

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [11]:
#rep(0, times = 40)
#easiset way
print([0]*40)
print('*'*79)
#list comprehension
rep = [0 for i in range(40)]
print(rep)
print(len(rep))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
*******************************************************************************
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
40


In [12]:
#rep(c(0, 1, 2), times = 10)
print([0,1,2]*10)
#the python's equivalent of R's rep() is the list multiplication

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


In [13]:
#rep(c(0, 1, 2), each = 10)
print([j for j in [0,1,2] for i in range(10)])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


# 4. Vectors

In [14]:
#num_vect <- c(0.5, 5.5, -10, 6)
num_vect = [0.5, 55, -10, 6]
print(num_vect)

[0.5, 55, -10, 6]


In [15]:
#tf <- num_vect < 1
tf = [i<1 for i in num_vect]
print(tf)

[True, False, True, False]


In [16]:
#num_vect >= 6
print([i>=6 for i in num_vect])

[False, True, False, True]


In [17]:
#(3 > 5) & (4 == 4)
(3 > 5) & (4 == 4)

False

In [18]:
#(TRUE == TRUE) | (TRUE == FALSE)
(True == True) | (True == False)

True

Logical operators in python
+ == equals
+ != different from
+ not opposite of

In [19]:
#((111 >= 111) | !(TRUE)) & ((4 + 1) == 5)
((111 >= 111) | (not True)) & ((4 + 1) == 5)

True

In [20]:
#my_char <- c("My", "name", "is")
my_char = ["My", "name", "is"]
print(my_char)

['My', 'name', 'is']


In [21]:
#paste(my_char, collapse = " ")
print(' '.join(my_char))

My name is


In [22]:
#my_name <- c(my_char, "Arnaud")
my_name = my_char + ['Arnaud']
print(my_name)
print([my_char, 'Thérèse'])

['My', 'name', 'is', 'Arnaud']
[['My', 'name', 'is'], 'Thérèse']


In [23]:
#paste("Hello", "world!", sep = " ")
print("Hello", "world!", sep = " ")

Hello world!


In [24]:
#paste(1:3, c("X", "Y", "Z"), sep = "")
print([ str(i)+j for (i,j) in zip(list(range(1,4)), ["X", "Y", "Z"])])

['1X', '2Y', '3Z']


The iterables need to be a pair of elements,so we need to use the zip function to convert a pair of 3 elements to a list of 3 pairs

**NB: use of zip()**

lambda x:list(zip(x)) is the python equivalent of the transposition in algebra


In [25]:
print(list(zip(list(range(1,4)), ["X", "Y", "Z"])))
print((list(range(1,4)), ["X", "Y", "Z"]))

[(1, 'X'), (2, 'Y'), (3, 'Z')]
([1, 2, 3], ['X', 'Y', 'Z'])


In [26]:
#paste(LETTERS, 1:4, sep = "-")
import itertools
LETTERS = list("A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S" "T" "U" "V" "W" "X" "Y" "Z")
print([ j+str(i) for (i,j) in zip(itertools.cycle(range(1,5)), LETTERS)])

['A1', 'B2', 'C3', 'D4', 'E1', 'F2', 'G3', 'H4', 'I1', 'J2', 'K3', 'L4', 'M1', 'N2', 'O3', 'P4', 'Q1', 'R2', 'S3', 'T4', 'U1', 'V2', 'W3', 'X4', 'Y1', 'Z2']


To replicate R's behaviour of looping until the longest list ends, we need to nest the shortest iterator with the itertools.cycle() function.

NB: if we use 
 + itertools.cycle() with itertools.zip_longest() instead of zip()
 + itertools.cycle() on both iterators 

we will end up with an infinte loop that will blow our computer memory


In [27]:
print(list(zip(list(range(1,4)), list(LETTERS))))
print(79*'*')
print(list(itertools.zip_longest(list(range(1,4)), list(LETTERS))))

[(1, 'A'), (2, 'B'), (3, 'C')]
*******************************************************************************
[(1, 'A'), (2, 'B'), (3, 'C'), (None, 'D'), (None, 'E'), (None, 'F'), (None, 'G'), (None, 'H'), (None, 'I'), (None, 'J'), (None, 'K'), (None, 'L'), (None, 'M'), (None, 'N'), (None, 'O'), (None, 'P'), (None, 'Q'), (None, 'R'), (None, 'S'), (None, 'T'), (None, 'U'), (None, 'V'), (None, 'W'), (None, 'X'), (None, 'Y'), (None, 'Z')]


**R**

Also worth noting is that the numeric vector 1:4 gets 'coerced' into a character vector by the paste() function.

**python**

R's coercion concept is called casting in python and other "low-level" programming languages (C++, Java). In python casting needs to be explicitely performed through the use of the str() function

# 5. Missing values

In [28]:
#in python, NaN is not handled by default, but the numpy package implements it
import numpy as np
np.nan

nan

In [29]:
# x <- c(44, NA, 5, NA)
x = [44, np.nan, 5, np.nan]
print(x)

[44, nan, 5, nan]


In [30]:
# x*3
print([3*a for a in x])

[132, nan, 15, nan]


In [31]:
#y <- rnorm(1000)
y = np.random.rand(10)
print(y[:23])

[  1.82658656e-02   5.56473423e-01   7.32087733e-02   6.44883479e-01
   8.31305560e-01   4.49926951e-01   6.27780103e-01   6.23305040e-04
   8.85043183e-01   7.34694189e-02]


In [32]:
#z <- rep(NA, 1000)
z = [np.nan]*10
print(z[:23])

[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]


In [33]:
#my_data <- sample(c(y, z), 100)
# python's equivalent of R's sample() function is np.random.choice(),
# but it takes only 1 list as argument, so we have to concatenate the 2 lists in 1 first
my_data = z[:] #avoid modifying z 
#NB: my_data = z set the 'z' and 'my_data' pointers to the same address
my_data.extend(y)
my_data = np.random.choice(my_data,100)
print(my_data[:23])

[        nan  0.07320877         nan  0.64488348         nan  0.64488348
         nan         nan  0.01826587  0.01826587  0.6277801          nan
         nan  0.01826587         nan  0.01826587         nan  0.88504318
  0.07346942  0.88504318         nan         nan  0.44992695]


In [34]:
#my_na <- is.na(my_data)
my_na = [np.isnan(a) for a in my_data]
print(my_na)
#other option (numpy works similarly as R)
# NB: on a large list, this solution is slower than the first one, which uses low-level syntax
print(79*"*")
my_na2 = np.isnan(my_data)
print(my_na)

[True, False, True, False, True, False, True, True, False, False, False, True, True, False, True, False, True, False, False, False, True, True, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, True, False, False, False, True, True, False, True, True, True, True, True, False, False, True, False, False, False, True, False, True, True, True, True, False, False, True, True, False, True, False, False, False, True, True, False, False, True, False, False, True, False, True, True, True, False, False, True, False, False, False, False, False, False, True, False, False, True, True, False, True, False, False]
*******************************************************************************
[True, False, True, False, True, False, True, True, False, False, False, True, True, False, True, False, True, False, False, False, True, True, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, True, False,

In [35]:
#sum(my_na)
sum(my_na)
#once in a while pyhton and R match =)

41

In [36]:
#0/0
0/0
# R returns nan, python throws an error

ZeroDivisionError: division by zero

# 6. Subsetting Vectors

In [37]:
import numpy as np
x = list(np.random.rand(20))
x.extend([np.nan]*20)
print(x)

[0.72273237543265956, 0.043760110666245744, 0.74358482414683236, 0.8618010299126595, 0.057467361165623898, 0.39746586738433853, 0.38257964821204549, 0.68719454746351993, 0.92649772479021808, 0.75153126289981165, 0.44571566725401035, 0.78504880691747936, 0.68732690739718161, 0.95454321772941253, 0.57570144128889467, 0.42160260507014768, 0.71786737620490981, 0.37526820610084821, 0.052401334037102898, 0.78278225653871669, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]


In [38]:
#x[1:10]
print(x[:10])
print(len(x[:10]))
#in python, indexes start at 0 and slicing does not include the last index

[0.72273237543265956, 0.043760110666245744, 0.74358482414683236, 0.8618010299126595, 0.057467361165623898, 0.39746586738433853, 0.38257964821204549, 0.68719454746351993, 0.92649772479021808, 0.75153126289981165]
10


In [39]:
#y <- x[!is.na(x)]
y = [a for a in x if not np.isnan(a)]
print(y)
print(len(y))

[0.72273237543265956, 0.043760110666245744, 0.74358482414683236, 0.8618010299126595, 0.057467361165623898, 0.39746586738433853, 0.38257964821204549, 0.68719454746351993, 0.92649772479021808, 0.75153126289981165, 0.44571566725401035, 0.78504880691747936, 0.68732690739718161, 0.95454321772941253, 0.57570144128889467, 0.42160260507014768, 0.71786737620490981, 0.37526820610084821, 0.052401334037102898, 0.78278225653871669]
20


In [40]:
#y[y > 0] 
print([a for a in y if a> 0] )

[0.72273237543265956, 0.043760110666245744, 0.74358482414683236, 0.8618010299126595, 0.057467361165623898, 0.39746586738433853, 0.38257964821204549, 0.68719454746351993, 0.92649772479021808, 0.75153126289981165, 0.44571566725401035, 0.78504880691747936, 0.68732690739718161, 0.95454321772941253, 0.57570144128889467, 0.42160260507014768, 0.71786737620490981, 0.37526820610084821, 0.052401334037102898, 0.78278225653871669]


In python, nan numbers always return False when used in a boolean expression

In [41]:
print(np.nan == True)
print(np.nan == False)
print(np.nan > 1)

False
False
False


In [42]:
#x[c(3,5,7)]
[x[3], x[5], x[7]]

[0.8618010299126595, 0.39746586738433853, 0.68719454746351993]

In [43]:
#x[c(-2, -10)]
res = x[:2]
res.extend(x[3:10])
res.extend(x[11:])
print(res)
print(len(res))

#other method
print('*'*79)
res = x[:]
res.pop(1)
res.pop(9)
print(res)
print(len(res))

[0.72273237543265956, 0.043760110666245744, 0.8618010299126595, 0.057467361165623898, 0.39746586738433853, 0.38257964821204549, 0.68719454746351993, 0.92649772479021808, 0.75153126289981165, 0.78504880691747936, 0.68732690739718161, 0.95454321772941253, 0.57570144128889467, 0.42160260507014768, 0.71786737620490981, 0.37526820610084821, 0.052401334037102898, 0.78278225653871669, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
38
*******************************************************************************
[0.72273237543265956, 0.74358482414683236, 0.8618010299126595, 0.057467361165623898, 0.39746586738433853, 0.38257964821204549, 0.68719454746351993, 0.92649772479021808, 0.75153126289981165, 0.78504880691747936, 0.68732690739718161, 0.95454321772941253, 0.57570144128889467, 0.42160260507014768, 0.71786737620490981, 0.37526820610084821, 0.052401334037102898, 0.78278225653871669, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, n

In python, "named lists" are called dictionnaries. They have the same kind of features as R's string-keyed lists.

In [44]:
#vect <- c(foo = 11, bar = 2, norf = NA)
dic = {'foo': 11, 'bar': 2, 'norf': np.nan}
print(dic)

{'foo': 11, 'bar': 2, 'norf': nan}


In [45]:
#names(vect)
print(list(dic.keys()))

['foo', 'bar', 'norf']


In [46]:
#vect2 <- c(11, 2, NA)
#names(vect2) <- c("foo", "bar", "norf")
dic2 = dict(zip(['foo', 'bar', 'norf'], [11,2, np.nan]))
print(dic2)

{'foo': 11, 'bar': 2, 'norf': nan}


In [47]:
#identical(vect,vect2)
dic == dic2

True

In [48]:
#vect["bar"]
print(dic["bar"])
#vect[c("foo", "bar")]
print({k:v for (k,v) in dic.items() if k in ['foo', 'bar']})

2
{'foo': 11, 'bar': 2}


In python, comprehension also works for dictionnaries

# 7. Matrices and Data Frames

In python, matrices are implemented in the *numpy* package while data frames are implemented in the *pandas* package. Here are the corresponding documentations
 + __[np.matrix](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html)__
 + __[DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html)__

In [49]:
#my_vector <- 1:20
my_vector = list(range(1,21))
print(my_vector)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [50]:
#dim(my_vector)
#in python the dimension function *dim* is also not implemented for lists
my_vector.ndim()

AttributeError: 'list' object has no attribute 'ndim'

In [51]:
#length(my_vector)
len(my_vector)

20

In [52]:
#dim(my_vector) <- c(4, 5)
my_matrix = np.matrix([my_vector[i:i+5] for i in range(4)])
print(my_matrix)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [53]:
#class(my_vector)
print(type(my_vector))
print(type(my_matrix))

<class 'list'>
<class 'numpy.matrixlib.defmatrix.matrix'>


In [54]:
#patients <- c("Bill", "Gina", "Kelly", "Sean")
patients = ["Bill", "Gina", "Kelly", "Sean"]

In [55]:
#cbind(patients, my_matrix)
#python does not allow this confusing syntax

In [56]:
#my_data <- data.frame(patients, my_matrix)
import pandas as pd
my_data = pd.DataFrame(index = patients, data = my_matrix)
print(my_data)
#NB: if we want to ommit the labels, we have to put the data first and then then index.
print('*'*79)
print(pd.DataFrame( my_matrix, patients))

       0  1  2  3  4
Bill   1  2  3  4  5
Gina   2  3  4  5  6
Kelly  3  4  5  6  7
Sean   4  5  6  7  8
*******************************************************************************
       0  1  2  3  4
Bill   1  2  3  4  5
Gina   2  3  4  5  6
Kelly  3  4  5  6  7
Sean   4  5  6  7  8


In [57]:
#class(my_data)
print(type(my_data))

<class 'pandas.core.frame.DataFrame'>


In [58]:
#cnames <- c("patient", "age", "weight", "bp", "rating", "test")
#colnames(my_data) <- cnames
my_data.columns = ["age", "weight", "bp", "rating", "test"]
my_data.index.name = 'patient' # in python column and index names are handled separately
print(my_data)

         age  weight  bp  rating  test
patient                               
Bill       1       2   3       4     5
Gina       2       3   4       5     6
Kelly      3       4   5       6     7
Sean       4       5   6       7     8


# 8. Looking at data

ToDo:
+ save the *plants* data in a csv file
+ load it with Python
+ do the chapter

In [59]:
#ls()
print(dir())

['In', 'LETTERS', 'Out', '_', '_17', '_18', '_19', '_2', '_28', '_35', '_42', '_47', '_51', '_7', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_dh', '_i', '_i1', '_i10', '_i11', '_i12', '_i13', '_i14', '_i15', '_i16', '_i17', '_i18', '_i19', '_i2', '_i20', '_i21', '_i22', '_i23', '_i24', '_i25', '_i26', '_i27', '_i28', '_i29', '_i3', '_i30', '_i31', '_i32', '_i33', '_i34', '_i35', '_i36', '_i37', '_i38', '_i39', '_i4', '_i40', '_i41', '_i42', '_i43', '_i44', '_i45', '_i46', '_i47', '_i48', '_i49', '_i5', '_i50', '_i51', '_i52', '_i53', '_i54', '_i55', '_i56', '_i57', '_i58', '_i59', '_i6', '_i7', '_i8', '_i9', '_ih', '_ii', '_iii', '_oh', '_sh', 'a', 'by', 'dic', 'dic2', 'end', 'exit', 'get_ipython', 'itertools', 'math', 'my_char', 'my_data', 'my_matrix', 'my_na', 'my_na2', 'my_name', 'my_seq', 'my_vector', 'nb', 'np', 'num_vect', 'patients', 'pd', 'quit', 'rep', 'res', 'start', 'tf', 'x', 'y', 'z']


In [60]:
#class(plants)


In [61]:
#dim(plants)


In [62]:
#nrow(plants)

In [63]:
#ncol(plants)

In [64]:
#object.size(plants)

In [65]:
#names(plants)
print(plants.columns.name)

NameError: name 'plants' is not defined

In [ ]:
#head(plants)
plants.head()

In [ ]:
#head(plants,10)
plants.head(10)

In [ ]:
#tail(plants,15)
plants.tail(15)

In [ ]:
#summary(plants)


# 9. Base graphics

ToDo:
+ learn ggplot2
+ do the chapter in Python